<a href="https://colab.research.google.com/github/bathicodes/EXPERIMENTS/blob/main/ANN_for_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import packages

In [164]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

### Import dataset 

In [165]:
dataset = pd.read_csv('Iris.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [166]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [167]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

### Data preprocessing

In [168]:
le = LabelEncoder()
y = le.fit_transform(y)

In [169]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Split to training set and testing set

In [170]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

### Feature scaling

In [171]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

### Creating Artificial Neural Network

In [172]:
ann = tf.keras.models.Sequential()

In [173]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [174]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [175]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [176]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

### Training the Artificial Neural Network

In [177]:
ann.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [178]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 3ms/step - loss: 0.9702 - accuracy: 0.3667
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9565 - accuracy: 0.3667
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9431 - accuracy: 0.3667
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9317 - accuracy: 0.3750
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9205 - accuracy: 0.3833
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9106 - accuracy: 0.4167
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9013 - accuracy: 0.4417
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8918 - accuracy: 0.4500
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8834 - accuracy: 0.4750
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 0.8750 - accuracy: 0.4833
Epoch 11/100
4/4 [===========

### Making new predictions

In [179]:
print(ann.predict(sc.transform([[5.0,2.0,3.5,1.0]])))
predict = ann.predict(sc.transform([[5.0,2.0,3.5,1.0]]))
index = np.argmax(predict)
print(index)

[[0.02861668 0.52323663 0.4481467 ]]
1


### Predicting the test set results

In [180]:
y_pred = ann.predict(x_test)
new_y = []
for i in y_pred:
  new_y_pred = np.argmax(i)
  new_y.append(new_y_pred)

y_pred_value = np.array(new_y)

print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_value.reshape(len(y_pred_value),1)),1))

[[2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [1 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [0 0]
 [1 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


### Making the confusion matrix

In [181]:
cm = confusion_matrix(y_test, y_pred_value)
print(cm)

[[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]


### Accuracy score

In [182]:
ac = accuracy_score(y_test, y_pred_value)
print(ac)

0.8333333333333334
