<a href="https://colab.research.google.com/github/bathicodes/EXPERIMENTS/blob/main/Mines_vs_Rocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import libraries

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Import dataset

In [59]:
dataset = pd.read_csv('sonar data.csv')

### Get information about dataset

In [72]:
dataset.isnull().sum()
dataset.describe()
dataset.info()
dataset['R'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0.0200  207 non-null    float64
 1   0.0371  207 non-null    float64
 2   0.0428  207 non-null    float64
 3   0.0207  207 non-null    float64
 4   0.0954  207 non-null    float64
 5   0.0986  207 non-null    float64
 6   0.1539  207 non-null    float64
 7   0.1601  207 non-null    float64
 8   0.3109  207 non-null    float64
 9   0.2111  207 non-null    float64
 10  0.1609  207 non-null    float64
 11  0.1582  207 non-null    float64
 12  0.2238  207 non-null    float64
 13  0.0645  207 non-null    float64
 14  0.0660  207 non-null    float64
 15  0.2273  207 non-null    float64
 16  0.3100  207 non-null    float64
 17  0.2999  207 non-null    float64
 18  0.5078  207 non-null    float64
 19  0.4797  207 non-null    float64
 20  0.5783  207 non-null    float64
 21  0.5071  207 non-null    float64
 22  0.

M    111
R     96
Name: R, dtype: int64

In [61]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

### Encode label

In [62]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

### Split dataset into training and test set

In [63]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,random_state=1)

### Feature scaling

In [64]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

### Training logistic regression on training data

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

classifier = LogisticRegression()
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[11  1]
 [ 3  6]]
0.8095238095238095
K Fold Cross validation: 80.58 %
Standard diviation: 5.69 %


### Training k nearest neighbour on training data

In [75]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[12  0]
 [ 2  7]]
0.9047619047619048
K Fold Cross validation: 83.89 %
Standard diviation: 7.82 %


### Training svm on training data

In [76]:
from sklearn.svm import SVC

classifier = SVC(kernel='linear',random_state=0)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[11  1]
 [ 4  5]]
0.7619047619047619
K Fold Cross validation: 78.95 %
Standard diviation: 5.96 %


### Training kernel svm on training data

In [77]:
classifier = SVC(kernel='rbf',random_state=0)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[12  0]
 [ 2  7]]
0.9047619047619048
K Fold Cross validation: 83.89 %
Standard diviation: 7.82 %


### Training naive bayes on training data

In [78]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[5 7]
 [2 7]]
0.5714285714285714
K Fold Cross validation: 65.76 %
Standard diviation: 11.14 %


### Training decision tree classification on training data

In [79]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(random_state=0)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[10  2]
 [ 2  7]]
0.8095238095238095
K Fold Cross validation: 72.46 %
Standard diviation: 9.38 %


### Training random forest classification on training data

In [80]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=10,random_state=0)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
print('K Fold Cross validation: {:.2f} %'.format(accuracies.mean() * 100))
print('Standard diviation: {:.2f} %'.format(accuracies.std() * 100))

[[10  2]
 [ 3  6]]
0.7619047619047619
K Fold Cross validation: 77.95 %
Standard diviation: 6.17 %
